### ISSUE TITLE
'Like' icon change suggestion

### ISSUE THREAD

**Issue by scottmcdaniel** [sharecuts/website#42]
As you may or may not be aware, the 👌 emoji (and its real life counterpart gesture) has been appropriated by the extreme right wing, including white supremacists and others.

To avoid any misunderstanding, I would propose changing the 'like' icon to something more nuetral. Some possible suggestions include: 😎👍🔥🥇💙✅

Or you could give the site a logo/mascot and use that as the indicator. Lots of options to choose from!  You could even possibly use a unicode cuneiform character, giving it a specific color or size.   𒐯

Just a thought, hope it helps!

**Comment by insidegui** [comment]
I'm happy with the way it is right now.
